### ISSUE TITLE
Deshabilitar actualización de Dir3 via Quartz

### ISSUE THREAD

**Issue by ibarrancos** [carm-es/csvstorage#14]
Se debe deshabilitar la actualización automática de Dir3 programada en Quartz, para evitar que la orgánica Dir3 sea distinta a la de Inside 

Issue relacionado: #13

**Comment by ibarrancos** [comment]
Después de mirar el código, descubro que la programación de QUARTZ no está en ficheros .properties, sino en la propia base de datos.

Podemos deshabilitar que se ejecute el cron de la actualización de orgánicas de DIR3, indicando que se ejecute en un año ya pasado:

``` 
UPDATE qrtz_cron_triggers 
   SET cron_expression='0 0 4 ? * MON 1989'
 WHERE trigger_group='unidaddir3';

SELECT * from qrtz_cron_triggers;

COMMIT;
```

**Comment by ibarrancos** [comment]
@alp23g 

Antonio, revisa por favor que en las bases de datos de desarrollo y producción de CSVStorage está aplicado el cambio, y cierra el ticket cuando lo hayas hecho.

Yo ya lo he aplicado en pruebas.

**Comment by ibarrancos** [comment]
El [commit 5ddbac1](https://github.com/carm-es/csvstorage/commit/5ddbac1440eefacdd4ce6b78584d2b8bd9c544b9) en el que se configuraba una fecha del año 1989 provoca una **excepción en el inicio del Tomcat, en la QUARTZ se queja de que nunca se ejecutará**.

```
2019-10-11 03:01:34.393+0200 2019-10-11 03:01:33,015  INFO QuartzScheduler:240 - Quartz Scheduler v.2.2.1 created.
2019-10-11 03:01:34.393+0200 2019-10-11 03:01:33,030  INFO QuartzScheduler:305 - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'schedulerFactoryBean' with instanceId 'servapp-des-sa3.carm.es1570755692997'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 5 threads.
  Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.
2019-10-11 03:01:34.393+0200 2019-10-11 03:01:33,030  INFO StdSchedulerFactory:1339 - Quartz scheduler 'schedulerFactoryBean' initialized from an externally provided properties instance.
2019-10-11 03:01:34.393+0200 2019-10-11 03:01:33,031  INFO StdSchedulerFactory:1343 - Quartz scheduler version: 2.2.1
2019-10-11 03:01:34.393+0200 2019-10-11 03:01:33,031  INFO QuartzScheduler:2311 - JobFactory set to: es.gob.aapp.csvstorage.configuration.AutowiringSpringBeanJobFactory@3ff5dc13
2019-10-11 03:01:34.393+0200 2019-10-11 03:01:33,695  WARN AnnotationConfigEmbeddedWebApplicationContext:551 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schedulerFactoryBean' defined in class path resource [es/gob/aapp/csvstorage/configuration/QuartzConfiguration.class]: Invocation of init method failed; nested exception is org.quartz.SchedulerException: Based on configured schedule, the given trigger will never fire.
2019-10-11 03:01:34.393+0200 2019-10-11 03:01:33,699  INFO LocalContainerEntityManagerFactoryBean:590 - Closing JPA EntityManagerFactory for persistence unit 'default'
2019-10-11 03:01:34.393+0200 2019-10-11 03:01:33,712 ERROR SpringApplication:821 - Application startup failed
2019-10-11 03:01:34.393+0200 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schedulerFactoryBean' defined in class path resource [es/gob/aapp/csvstorage/configuration/QuartzConfiguration.class]: Invocation of init method failed; nested exception is org.quartz.SchedulerException: Based on configured schedule, the given trigger will never fire.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:150)
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:130)
	at es.gob.aapp.csvstorage.ExternalServerInitializer.onStartup(ExternalServerInitializer.java:47)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.quartz.SchedulerException: Based on configured schedule, the given trigger will never fire.
	at org.quartz.core.QuartzScheduler.rescheduleJob(QuartzScheduler.java:1142)
	at org.quartz.impl.StdScheduler.rescheduleJob(StdScheduler.java:321)
	at org.springframework.scheduling.quartz.SchedulerAccessor.addTriggerToScheduler(SchedulerAccessor.java:302)
	at org.springframework.scheduling.quartz.SchedulerAccessor.registerJobsAndTriggers(SchedulerAccessor.java:235)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:527)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 29 more
2019-10-11 03:01:34.393+0200 2019-10-11 03:01:33,717  WARN SpringApplication:91 - Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available)
2019-10-11 03:01:34.394+0200 11-Oct-2019 03:01:33.718 GRAVE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/csvstorage]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schedulerFactoryBean' defined in class path resource [es/gob/aapp/csvstorage/configuration/QuartzConfiguration.class]: Invocation of init method failed; nested exception is org.quartz.SchedulerException: Based on configured schedule, the given trigger will never fire.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:150)
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:130)
	at es.gob.aapp.csvstorage.ExternalServerInitializer.onStartup(ExternalServerInitializer.java:47)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: org.quartz.SchedulerException: Based on configured schedule, the given trigger will never fire.
	at org.quartz.core.QuartzScheduler.rescheduleJob(QuartzScheduler.java:1142)
	at org.quartz.impl.StdScheduler.rescheduleJob(StdScheduler.java:321)
	at org.springframework.scheduling.quartz.SchedulerAccessor.addTriggerToScheduler(SchedulerAccessor.java:302)
	at org.springframework.scheduling.quartz.SchedulerAccessor.registerJobsAndTriggers(SchedulerAccessor.java:235)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:527)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 29 more
2019-10-11 03:01:34.394+0200 11-Oct-2019 03:01:33.720 GRAVE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error durante el despliegue del archivo [/opt/tomcat-csvstorage/webapps/csvstorage.war] de la aplicaciÃ³n web
```

**Comment by alp23g** [comment]
Compruebo que en todos los entornos se queda a nivel BD correctamente la expresión cron que debe ser ésta `0 0 4 ? * MON 2049` para que no salte. Se actualiza correctamente al arrancar la aplicación. Además, para asegurarnos de que ésto queda documentado, también modifico el script de creación del esquema porque hace un insert - DDL en este [commit](https://github.com/carm-es/csvstorage/commit/473cad0733977100dd5b8dce8a6b2ba169c77010)
